#!/bin/bash

#source /reg/g/pcds/setup/epicsenv-3.14.12.sh
source /reg/g/psdm/sw/conda2/manage/bin/psconda.sh ""
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export PATH=$SCRIPTDIR/../../../install/bin:${PATH}
#export EPICS_CAS_INTF_ADDR_LIST=$(/bin/hostname -i)
export EPICS_CA_SERVER_PORT=5066
export EPICS_CA_REPEATER_PORT=5067

###################################################################################
# Start python from a here document
###################################################################################

#python2.7 "$@"
python "$@"
