export INCLUDE_PGP3_10G = 0
#export REMOVE_UNUSED_CODE = 1

# Define Firmware Version Number
export PRJ_VERSION = 0x00000012

# Define target part
export PRJ_PART = xcku115-flvb2104-2-e

#simulation package export
export TIMING_EXT_PKG = 1

# Define target output
target: prom

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
