XTC_VOL: DebugIter Class Reference
DebugIter Class Reference
Public Types
enum { Stop, Continue }
enum IteratorType { LIST_ALL, SEARCH, LIST_W_DEPTH, DEFAULT }
typedef enum DebugIter::IteratorType ItType
Public Member Functions
DebugIter ()
xtc_ds_info * get_ds_info (int index, ShapesData *shapesdata, xtc_dgram_info &dgram_info)
size_t get_data (xtc_object *xtc_obj, size_t pixel_cnt, void *data_out)
void get_value (int i, Name &name, DescData &descdata)
int process (Xtc *xtc)
int process_list_all (Xtc *xtc)
void index_init ()
int get_index ()
void append_token (string str)
void set_input_path (vector< string > str_vec)
int compare_input_path ()
void pop_token ()
void print_input_path ()
void print_local_path (void)
string get_current_path ()
void set_iterator_type (ItType type)
ItType get_iterator_type ()
void xtc_tree_init (xtc_object *root_obj)
void xtc_tree_init (int fd)
int xtc_tree_node_add (xtc_node *node)
xtc_node * xtc_tree_node_find (const char *target_path)
xtc_node * xtc_tree_node_find (string *target_path_in)
xtc_node * get_root ()
int xtc_tree_print ()
int attach_helper (xtc_object *h)
int detach_helper ()
xtc_object * get_helper ()
NamesLookup * namesLookup ()
void set_current_dgram (Dgram *dgram)
int find_index (uint64_t dgram_id, xtc_dgram_info *dgram_info_out)
int load_index (int index_fd)
int check_update_dgram (int fd, xtc_dgram_info *dg_info, Dgram *current_dgram_in_out)
int get_fd ()
Data Fields
int SCAN_DEPTH
vector< string > _INPUT_PATH_TOKENS
xtc_location * CURRENT_LOCATION
vector< string > _CURRENT_PATH_TOKENS
Dgram * _current_dgram
Detailed Description
Customized XTC iterator, it's the core part to read xtc2 file. It read the file, and extract hierarchy information and store in a index tree.
Definition at line 109 of file xtc_io_api.cc.
Member Typedef Documentation
ItType
typedef enum DebugIter::IteratorType ItType
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Stop
Continue
Definition at line 112 of file xtc_io_api.cc.
 { Stop, Continue };
IteratorType
enum IteratorType
Enumerator
LIST_ALL
SEARCH
LIST_W_DEPTH
DEFAULT
Definition at line 828 of file xtc_io_api.cc.
{
         LIST_ALL,
         SEARCH,
         LIST_W_DEPTH,
         DEFAULT
     }ItType;
Constructor & Destructor Documentation
DebugIter()
DebugIter () inline
Definition at line 113 of file xtc_io_api.cc.
                 : XtcIterator()
     {
     }
Member Function Documentation
append_token()
void append_token (string str) inline
Definition at line 781 of file xtc_io_api.cc.
{
         _CURRENT_PATH_TOKENS.push_back(str);
         _index_increment();
     }
Referenced by iterate_list_all().
attach_helper()
int attach_helper (xtc_object * h) inline
Definition at line 879 of file xtc_io_api.cc.
{
         assert(h);
         h->ref_cnt++;
         return 0;
     }
References XTC_C_API_HELPER::ref_cnt.
check_update_dgram()
int check_update_dgram (int fd, xtc_dgram_info * dg_info, Dgram * current_dgram_in_out) inline
Check if the current dgram is the target, if not, load dgram from xtc2 file.
Definition at line 982 of file xtc_io_api.cc.
{
         assert(dg_info && current_dgram_in_out);
         static const unsigned bigdgBufferSize = 0x4000000;
         DEBUG_PRINT
         if((current_dgram_in_out)->time.value() != dg_info->dgram_id){
             printf("dgram_id(0x%llx) doesn't match current one(0x%llx), load dgram ...\n",
                     dg_info->dgram_id, (current_dgram_in_out)->time.value());
             if(dg_info->ds_type == DS_NON_L1 || dg_info->dgram_offset <= 0){//Non-L1 dgrams
                 DEBUG_PRINT
                 assert(dg_info->isL1 == 0 && dg_info->nonL1Dgram);
                 *current_dgram_in_out = *(Dgram*)(dg_info->nonL1Dgram);
                 //verify
                 printf("Checking current_dgram_in_out.xtc.extent = %d, new dgram_id = 0x%llx, sizeofPayload = %d\n",
                         current_dgram_in_out->xtc.extent, current_dgram_in_out->time.value(), current_dgram_in_out->xtc.sizeofPayload());
             } else if (dg_info->ds_type == DS_L1){ // L1 dgrams
                 //move cursor to the where the offset points to
                 DEBUG_PRINT
                 if (lseek(fd, (off_t)(dg_info->dgram_offset), SEEK_SET) < 0) {
                     printf("lseek error\n");
                     return -1;
                 }
                 //Read dgram head.
                 if (::read(fd, current_dgram_in_out, sizeof(Dgram)) == 0) {//read from the offset to bigdg
                     printf("Data dgram header read error\n");
                     return -1;
                 }
                 //Check dgram size
                 unsigned bigdgsize = sizeof(Dgram)+current_dgram_in_out->xtc.extent;
                 if (bigdgsize>bigdgBufferSize) {
                     printf("Big dgram too large %s\n",bigdgsize);
                     exit(-1);
                 }
                 // why no to move a sizeof(Dgram) offset???
                 //Read dgram data
                 if (::read(fd, current_dgram_in_out->xtc.payload(), current_dgram_in_out->xtc.extent) == 0) {
                     printf("Big dgram payload read error\n");
                     exit(-1);
                 }
             } else {
                 DEBUG_PRINT
                 printf("Wrong type: should only be DS_NON_L1(1) or DS_L1(2). type = %d\n", dg_info->ds_type);
                 return -1;
             }
             DEBUG_PRINT
             printf(" done. Current dgram id = 0x%llx\n", (current_dgram_in_out)->time.value());
             return 0;
         }
         return 0;
     }
References DEBUG_PRINT, dgram_info::dgram_id, dgram_info::dgram_offset, DS_L1, DS_NON_L1, dgram_info::ds_type, dgram_info::isL1, and dgram_info::nonL1Dgram.
compare_input_path()
int compare_input_path () inline
Definition at line 789 of file xtc_io_api.cc.
{
         for(int i = 0; i < min(_INPUT_PATH_TOKENS.size(), _CURRENT_PATH_TOKENS.size()); i++){
             if(_INPUT_PATH_TOKENS[i].compare(_CURRENT_PATH_TOKENS[i]) != 0)
                 return -1;
         }
         if(_CURRENT_PATH_TOKENS.size() < _INPUT_PATH_TOKENS.size())
             return 1;//continue to scan
         if(_CURRENT_PATH_TOKENS.size() == _INPUT_PATH_TOKENS.size())
             return 0;//find a perfect match
         if(_CURRENT_PATH_TOKENS.size() > _INPUT_PATH_TOKENS.size())
             return 2;//scan too much, should return one step earlier.
         return 0;
     }
detach_helper()
int detach_helper () inline
Definition at line 885 of file xtc_io_api.cc.
{
         extern_helper->ref_cnt--;
         return 0;
     }
find_index()
int find_index (uint64_t dgram_id, xtc_dgram_info * dgram_info_out) inline
Find the dgram_info object by dgram_id from the dgram index map. Important info fields include dgram offset in the xtc2 file, transition type and presetned dataset type.
Definition at line 909 of file xtc_io_api.cc.
{
         assert(dgram_info_out);
         auto it = this->_index_map->find(dgram_id);
         if(it == _index_map->end()){
             printf("Dgram_id not exist! id = 0x%llx\n", dgram_id);
             return -1;
         } else {
             (*dgram_info_out).dgram_id = dgram_id;
             (*dgram_info_out).dgram_offset = it->second.dgram_offset;
             (*dgram_info_out).isL1 = it->second.isL1;
             (*dgram_info_out).nonL1Dgram = it->second.nonL1Dgram;
             (*dgram_info_out).ds_type = it->second.ds_type;
             return 0;
         }
     }
get_current_path()
string get_current_path () inline
Definition at line 816 of file xtc_io_api.cc.
{
         string ret("/");
         for(int i = 0; i < _CURRENT_PATH_TOKENS.size(); i++ ){
             ret += _CURRENT_PATH_TOKENS[i];
             if(i != _CURRENT_PATH_TOKENS.size() - 1)
                 ret += "/";
         }
         return ret;
     }
Referenced by iterate_list_all().
get_data()
size_t get_data (xtc_object * xtc_obj, size_t pixel_cnt, void * data_out) inline
Get data from nested and recursive xtc data structure and give it to dataset_read_all(). Only work with valid current Dgram, need to check the type before calling this, must be non-timestamp dataset.
Definition at line 200 of file xtc_io_api.cc.
                                                                           {//Names* namesd,
         xtc_data_handle* data_handle = xtc_obj->ds_info->data_handle;
         assert(data_handle);
         DEBUG_PRINT
         Dgram* sys_current_dgram = (Dgram*)xtc_obj->location->dg;
         printf("get_data: this = %p, sys_current_dgram = %p, \n", this, sys_current_dgram);
         assert(sys_current_dgram);
         if(data_handle->dgram_id != sys_current_dgram->time.value()){//different dgram, need to load.
             auto it =_index_map->find(data_handle->dgram_id);
             if(it == _index_map->end()){
                 printf("Can not find dgram info, id/timestamp = 0x%llx\n", data_handle->dgram_id);
                 return -1;
             } else {
                 printf(" Before: Current dgram id = 0x%llx\n", sys_current_dgram->time.value());
                 check_update_dgram(this->get_fd(), &(it->second), sys_current_dgram);
                 printf(" After: Current dgram id = 0x%llx\n", sys_current_dgram->time.value());
             }
         }
         ShapesData* shapesdata = (ShapesData*)((char*)sys_current_dgram + data_handle->dgram_info->shapesdata_offset);
         int index = data_handle->index;
         NamesId namesId = shapesdata->namesId();
         printf("namesId._value = 0x%lx\n", namesId.value());
         DescData descdata = DescData(*shapesdata, _namesLookup[namesId]);
         Names& names = descdata.nameindex().names();
         Name& name = names.get(index);
         assert(shapesdata);
         size_t pixel_size_out = 0;
         int data_rank = name.rank();
         int data_type = name.type();
         void* ret_data = NULL;
         char* tmp_buf = NULL;
         switch(name.type()){
         case(Name::UINT8):{
             assert(name.type() == xtc_data_type::UINT8);
             if(data_rank > 0){
                 Array<uint8_t> arrT = descdata.get_array<uint8_t>(index);
                 auto t = arrT.shape();
                 //rank == 3 5*6*7 is to describe the shape dimension of a element
                 //t[0] = 5, t[1]=6, t[2]=7
                 ret_data = arrT.data();
                     }
             else{
                 uint8_t val = descdata.get_value<uint8_t>(index);
                 ret_data = &val;
             }
             pixel_size_out = sizeof(uint8_t);
             break;
         }
         case(Name::UINT16):{
             assert(name.type() == xtc_data_type::UINT16);
             if(data_rank > 0){
                 Array<uint16_t> arrT = descdata.get_array<uint16_t>(index);
                 ret_data =arrT.data();
                     }
             else{
                 uint16_t val = descdata.get_value<uint16_t>(index);
                 ret_data =&val;
             }
             pixel_size_out = sizeof(uint16_t);
             break;
         }
         case(Name::UINT32):{
             assert(name.type() == xtc_data_type::UINT32);
             if(data_rank > 0){
                 Array<uint32_t> arrT = descdata.get_array<uint32_t>(index);
                 ret_data =arrT.data();
                     }
             else{
                 uint32_t val = descdata.get_value<uint32_t>(index);
                 ret_data =&val;
             }
             pixel_size_out = sizeof(uint32_t);
             break;
         }
         case(Name::UINT64):{
             assert(name.type() == xtc_data_type::UINT64);
             if(data_rank > 0){
                 Array<uint64_t> arrT = descdata.get_array<uint64_t>(index);
                 ret_data =arrT.data();
                     }
             else{
                 uint64_t val = descdata.get_value<uint64_t>(index);
                 ret_data =&val;
             }
             pixel_size_out = sizeof(uint64_t);
             break;
         }
         case(Name::INT8):{
             assert(name.type() == xtc_data_type::INT8);
             if(data_rank > 0){
                 Array<int8_t> arrT = descdata.get_array<int8_t>(index);
                 ret_data =arrT.data();
                     }
             else{
                 int8_t val = descdata.get_value<int8_t>(index);
                 ret_data =&val;
             }
             pixel_size_out = sizeof(int8_t);
             break;
         }
         case(Name::INT16):{
             assert(name.type() == xtc_data_type::INT16);
             if(data_rank > 0){
                 Array<int16_t> arrT = descdata.get_array<int16_t>(index);
                 ret_data =arrT.data();
                     }
             else{
                 int16_t val = descdata.get_value<int16_t>(index);
                 ret_data =&val;
             }
             pixel_size_out = sizeof(int16_t);
             break;
         }
         case(Name::INT32):{
             assert(name.type() == xtc_data_type::INT32);
             if(data_rank > 0){
                 Array<int32_t> arrT = descdata.get_array<int32_t>(index);
                 ret_data =arrT.data();
                     }
             else{
                 int32_t val = descdata.get_value<int32_t>(index);
                 ret_data =&val;
             }
             pixel_size_out = sizeof(int32_t);
             break;
         }
         case(Name::INT64):{
             assert(name.type() == xtc_data_type::INT64);
             if(data_rank > 0){
                 Array<int64_t> arrT = descdata.get_array<int64_t>(index);
                 ret_data =arrT.data();
                     }
             else{
                 int64_t val = descdata.get_value<int64_t>(index);
                 ret_data =&val;
             }
             pixel_size_out = sizeof(int64_t);
             break;
         }
         case(Name::FLOAT):{
             assert(name.type() == xtc_data_type::FLOAT);
             if(data_rank > 0){
                 DEBUG_PRINT
                 Array<float> arrT = descdata.get_array<float>(index);
                 DEBUG_PRINT
                 ret_data =arrT.data();
                 DEBUG_PRINT
                     }
             else{
                 float val = descdata.get_value<float>(index);
                 DEBUG_PRINT
                 ret_data =&val;
                 DEBUG_PRINT
             }
             DEBUG_PRINT
             pixel_size_out = sizeof(float);
             DEBUG_PRINT
             break;
         }
         case(Name::DOUBLE):{
             assert(name.type() == xtc_data_type::DOUBLE);
             DEBUG_PRINT
             if(data_rank > 0){
                 Array<double> arrT = descdata.get_array<double>(index);
                 ret_data =arrT.data();
                     }
             else{
                 double val = descdata.get_value<double>(index);
                 ret_data =&val;
             }
             pixel_size_out = sizeof(double);
             break;
         }
         case(Name::CHARSTR):{
             assert(name.type() == xtc_data_type::CHARSTR);
             assert(0);
             if(data_rank > 0){
                 Array<char> arrT = descdata.get_array<char>(index);
                 tmp_buf = (char*)calloc(arrT.num_elem() + 1, sizeof(char));
                 for(int i = 0; i < arrT.num_elem(); i++){
                     tmp_buf[i] = arrT.data()[i];
                 }
                 assert(0);
                 ret_data = &tmp_buf;
             }
             else{
                 char val = descdata.get_value<char>(index);
                 ret_data =&val;
             }
             DEBUG_PRINT
             assert(0);
             pixel_size_out = sizeof(char*);
             break;
         }
         case(Name::ENUMVAL):{
             assert(name.type() == xtc_data_type::ENUMVAL);
             if(data_rank > 0){
                 Array<int32_t> arrT = descdata.get_array<int32_t>(index);
                 ret_data =arrT.data();
                     }
             else{
                 int32_t val = descdata.get_value<int32_t>(index);
                 ret_data =&val;
             }
             pixel_size_out = sizeof(int32_t);
             break;
         }
         case(Name::ENUMDICT):{
             assert(name.type() == xtc_data_type::ENUMDICT);
             if(data_rank > 0){
                 ret_data =NULL;
             } else{
                 int32_t val = descdata.get_value<int32_t>(index);
                 ret_data =&val;
             }
             pixel_size_out = sizeof(int32_t);
             break;
         }
         default:
             assert(0 && "Unsupported type.");
             break;
         }
         size_t read_size = pixel_cnt * pixel_size_out;
         memcpy(data_out, ret_data, read_size);
         return read_size;
     }
References CHARSTR, check_update_dgram(), XTC_DS_info::data_handle, DEBUG_PRINT, Xtc_Location::dg, Xtc_dataset_handle::dgram_id, Xtc_dataset_handle::dgram_info, DOUBLE, XTC_C_API_HELPER::ds_info, ENUMDICT, ENUMVAL, FLOAT, Xtc_dataset_handle::index, INT16, INT32, INT64, INT8, XTC_C_API_HELPER::location, dgram_info::shapesdata_offset, UINT16, UINT32, UINT64, and UINT8.
Referenced by dataset_read_all().
get_ds_info()
xtc_ds_info* get_ds_info (int index, ShapesData * shapesdata, xtc_dgram_info & dgram_info) inline
Collect dataset information and build structures for HDF5 VOL to build data space, also includes the position info in the xtc2 file.
Definition at line 121 of file xtc_io_api.cc.
                                                                                            {//int i Names& names,
         NamesId namesId = shapesdata->namesId();
         DescData descdata(*shapesdata, _namesLookup[namesId]);
         DEBUG_PRINT
         Names& names = descdata.nameindex().names();
         xtc_ds_info* dataset_info = (xtc_ds_info*)calloc(1, sizeof(xtc_ds_info));
         Name& name = names.get(index);
         printf("get_ds_info: index = %d, shapesdata = %p, &shapesdata = %p, offset = %d, dgram_info.isL1 = %d, dgram = %p, dgram_id = 0x%llx, sizeofPayload = %d, field_name = [%s], str_type = [%s]\n",
                 index, shapesdata, &shapesdata, dgram_info.shapesdata_offset, dgram_info.isL1,
                 _current_dgram, _current_dgram->time.value(), _current_dgram->xtc.sizeofPayload(),
                 name.name(), name.str_type());
         dataset_info->type = (xtc_data_type)(int)(name.type());
         printf("get_ds_info: set data type: %d\n", dataset_info->type);
         dataset_info->dim_cnt = name.rank();//# of dimension: 0-5, how many dimensions of the shape:
         dataset_info->element_cnt = name.get_element_size(name.type());// how many elements
         dataset_info->maximum_dims = NULL;
         uint32_t* shape = descdata.shape(name);
         dataset_info->total_pixel_cnt = 1;
         if(name.type() == Name::CHARSTR){//single string
             dataset_info->dim_cnt = 1;
             dataset_info->current_dims[0] = 1;
         } else {
             for(int i = 0; i < name.rank(); i++)
                 dataset_info->current_dims[i] = shape[i];
             if(dataset_info->dim_cnt > 0){
                 printf("dim_cnt = %d, dimensions val: ", dataset_info->dim_cnt);
                 for(int i = 0; i < dataset_info->dim_cnt; i++){
                     dataset_info->total_pixel_cnt *= dataset_info->current_dims[i];
                     printf("%d, ", dataset_info->current_dims[i]);
                 }
                 printf("\n");
             }//dim_cnt == 0
         }
         if(dgram_info.ds_type < 0 || dgram_info.ds_type > 2){
             assert(0);
         }
         dataset_info->ds_type = dgram_info.ds_type;
         dataset_info->data_handle = (xtc_data_handle*)calloc(1, sizeof(xtc_data_handle));
         dataset_info->data_handle->dgram_id = dgram_info.dgram_id;
         dataset_info->data_handle->index = index;
         dataset_info->data_handle->dgram_info = (xtc_dgram_info*)calloc(1, sizeof(xtc_dgram_info));
         dataset_info->data_handle->dgram_info->dgram_id = dgram_info.dgram_id;
         dataset_info->data_handle->dgram_info->dgram_offset = dgram_info.dgram_offset;
         dataset_info->data_handle->dgram_info->shapesdata_offset = dgram_info.shapesdata_offset;
         dataset_info->data_handle->dgram_info->isL1 = dgram_info.isL1;
         dataset_info->data_handle->dgram_info->nonL1Dgram = dgram_info.nonL1Dgram;
         dataset_info->data_handle->dgram_info->ds_type = dgram_info.ds_type;
         DEBUG_PRINT
         dataset_info->data_handle->shapesData = calloc(1, sizeof(void*));
         memcpy(dataset_info->data_handle->shapesData, &shapesdata, sizeof(void*));
         DEBUG_PRINT
         DEBUG_PRINT
         printf("get_ds_info: index = %d, copied shapesdata address = %p\n", index, shapesdata);
         dataset_info->isTimestampsDS = 0;
         printf("get_ds_infodata_handle: xtc_ptr = %p\n",
                 dataset_info->data_handle->xtc_ptr);
         return dataset_info;
     }
References CHARSTR, XTC_DS_info::current_dims, XTC_DS_info::data_handle, DEBUG_PRINT, dgram_info::dgram_id, Xtc_dataset_handle::dgram_id, Xtc_dataset_handle::dgram_info, dgram_info::dgram_offset, XTC_DS_info::dim_cnt, dgram_info::ds_type, XTC_DS_info::ds_type, XTC_DS_info::element_cnt, Xtc_dataset_handle::index, dgram_info::isL1, XTC_DS_info::isTimestampsDS, XTC_DS_info::maximum_dims, dgram_info::nonL1Dgram, Xtc_dataset_handle::shapesData, dgram_info::shapesdata_offset, XTC_DS_info::total_pixel_cnt, XTC_DS_info::type, and Xtc_dataset_handle::xtc_ptr.
get_fd()
int get_fd () inline
Definition at line 1038 of file xtc_io_api.cc.
                 {
         return _fd;
     }
get_helper()
xtc_object* get_helper () inline
Definition at line 890 of file xtc_io_api.cc.
{
         return extern_helper;
     }
get_index()
int get_index () inline
Definition at line 777 of file xtc_io_api.cc.
                    {
         return _scan_index;
     }
get_iterator_type()
ItType get_iterator_type () inline
Definition at line 839 of file xtc_io_api.cc.
{
         return iterator_type;
     }
get_root()
xtc_node* get_root () inline
Definition at line 873 of file xtc_io_api.cc.
{
         return ROOT_NODE;
     }
get_value()
void get_value (int i, Name & name, DescData & descdata) inline
Print data value, used for demo and debugging.
Definition at line 450 of file xtc_io_api.cc.
{
         int data_rank = name.rank();
         int data_type = name.type();
         printf("get_value() terminal data entry ==============  %d: name:[%s], rank = %d, type = %d\n",
                 i, name.name(), data_rank, data_type);
         //printf("get_value() token = %s\n", name.name());
         switch(name.type()){
         case(Name::UINT8):{
             if(data_rank > 0){
                 Array<uint8_t> arrT = descdata.get_array<uint8_t>(i);
                 printf("type uint8_t: %s: %d, %d, %d\n",name.name(),arrT.data()[0],arrT.data()[1], arrT.data()[2]);
                     }
             else{
                 printf("type uint8_t:  %s: %d\n",name.name(),descdata.get_value<uint8_t>(i));
             }
             break;
         }
         case(Name::UINT16):{
             if(data_rank > 0){
                 Array<uint16_t> arrT = descdata.get_array<uint16_t>(i);
                 printf("type uint16_t:  %s: %d, %d, %d\n",name.name(),arrT.data()[0],arrT.data()[1], arrT.data()[2]);
                     }
             else{
                 printf("type uint16_t: %s: %d\n",name.name(),descdata.get_value<uint16_t>(i));
             }
             break;
         }
         case(Name::UINT32):{
             if(data_rank > 0){
                 Array<uint32_t> arrT = descdata.get_array<uint32_t>(i);
                 printf("type uint32_t: %s: %d, %d, %d\n",name.name(),arrT.data()[0],arrT.data()[1], arrT.data()[2]);
                     }
             else{
                 printf("type uint32_t: %s: %d\n",name.name(),descdata.get_value<uint32_t>(i));
             }
             break;
         }
         case(Name::UINT64):{
             if(data_rank > 0){
                 Array<uint64_t> arrT = descdata.get_array<uint64_t>(i);
                 printf("type uint64_t: %s: %d, %d, %d\n",name.name(),arrT.data()[0],arrT.data()[1], arrT.data()[2]);
                     }
             else{
                 printf("type uint64_t %s: %d\n",name.name(),descdata.get_value<uint64_t>(i));
             }
             break;
         }
         case(Name::INT8):{
             if(data_rank > 0){
                 Array<int8_t> arrT = descdata.get_array<int8_t>(i);
                 printf("type int8:  %s: %d, %d, %d\n",name.name(),arrT.data()[0],arrT.data()[1], arrT.data()[2]);
                     }
             else{
                 printf("type int8: %s: %d\n",name.name(),descdata.get_value<int8_t>(i));
             }
             break;
         }
         case(Name::INT16):{
             if(data_rank > 0){
                 Array<int16_t> arrT = descdata.get_array<int16_t>(i);
                 printf("type int16: %s: %d, %d, %d\n",name.name(),arrT.data()[0],arrT.data()[1], arrT.data()[2]);
                     }
             else{
                 printf("type int16: %s: %d\n",name.name(),descdata.get_value<int16_t>(i));
             }
             break;
         }
         case(Name::INT32):{
             if(data_rank > 0){
                 Array<int32_t> arrT = descdata.get_array<int32_t>(i);
                 printf("type int32: %s: %d, %d, %d\n",name.name(),arrT.data()[0],arrT.data()[1], arrT.data()[2]);
                     }
             else{
                 printf("type int32:   %s: %d\n",name.name(),descdata.get_value<int32_t>(i));
             }
             break;
         }
         case(Name::INT64):{
             if(data_rank > 0){
                 Array<int64_t> arrT = descdata.get_array<int64_t>(i);
                 printf("type int64:  %s: %d, %d, %d\n",name.name(),arrT.data()[0],arrT.data()[1], arrT.data()[2]);
                     }
             else{
                 printf("type int64:   %s: %d\n",name.name(),descdata.get_value<int64_t>(i));
             }
             break;
         }
         case(Name::FLOAT):{
             if(data_rank > 0){
                 Array<float> arrT = descdata.get_array<float>(i);
                 printf("type float:  %s: %f, %f\n",name.name(),arrT.data()[0],arrT.data()[1]);
                     }
             else{
                 printf("type float:  %s: %f\n",name.name(),descdata.get_value<float>(i));
             }
             break;
         }
         case(Name::DOUBLE):{
             if(data_rank > 0){
                 Array<double> arrT = descdata.get_array<double>(i);
                 printf("type double: %s: %f, %f, %f\n",name.name(),arrT.data()[0],arrT.data()[1], arrT.data()[2]);
                     }
             else{
                 printf("type double: %s: %f\n",name.name(),descdata.get_value<double>(i));
             }
             break;
         }
         case(Name::CHARSTR):{
             if(data_rank > 0){
                 Array<char> arrT = descdata.get_array<char>(i);
                 printf("type charstr:  rank = %d, num_elem = %lu, name = [%s], str = [%s], data() = %p \n",
                         arrT.rank(), arrT.num_elem(), name.name(), arrT.data(), arrT.data());
                     }
             else{
                 printf("type charstr: %s: string with 0 rank?!?\n",name.name());
             }
             break;
         }
         case(Name::ENUMVAL):{
             if(data_rank > 0){
                 Array<int32_t> arrT = descdata.get_array<int32_t>(i);
                 printf("type ENUMVAL: %s: %d, %d, %d\n",name.name(),arrT.data()[0],arrT.data()[1], arrT.data()[2]);
                     }
             else{
                 printf("type ENUMVAL %s: %d\n",name.name(),descdata.get_value<int32_t>(i));
             }
             break;
         }
         case(Name::ENUMDICT):{
             if(data_rank > 0){
                 printf("type ENUMDICT %s: enumdict with rank?!?\n", name.name());
             } else{
                 printf("type ENUMDICT  %s: %d\n",name.name(),descdata.get_value<int32_t>(i));
             }
             break;
         }
         }
     }
References CHARSTR, DOUBLE, ENUMDICT, ENUMVAL, FLOAT, INT16, INT32, INT64, INT8, UINT16, UINT32, UINT64, and UINT8.
index_init()
void index_init () inline
Definition at line 773 of file xtc_io_api.cc.
                      {
         _scan_index = -1;
     }
Referenced by iterate_list_all().
load_index()
int load_index (int index_fd) inline
Read the smd file and fill the dgram index in the map
Parameters
index_fd the file descriptor of the opened index file, which has the extension "smd".
Definition at line 928 of file xtc_io_api.cc.
{
         XtcFileIterator iter(index_fd, 0x4000000);
         unordered_map<uint64_t, xtc_dgram_info>* index_map = new unordered_map<uint64_t, xtc_dgram_info>;
         Dgram* smd_dgram;
         unsigned nevent=0;
         SmdIter smditer;
         printf("smditer.offset = 0x%llx\n", smditer.offset);
         while ((smd_dgram = iter.next())) {
             smditer.reset();
             smditer.iterate(&(smd_dgram->xtc));
             xtc_dgram_info info;
             info.dgram_id = smd_dgram->time.value();
             info.dgram_offset = smditer.offset;
             if(smditer.offset== (uint64_t)(int64_t)-1 ){//Non-L1 events, store in memory
                 printf("smd_dgram.dgram_id = 0x%llx, smd_dgram->xtc.extent = %d, smd_dgram->xtc.sizeofPayload() = %d\n",
                         smd_dgram->time.value(), smd_dgram->xtc.extent, smd_dgram->xtc.sizeofPayload());
                 size_t nonL1_dgram_size = sizeof(Dgram) + smd_dgram->xtc.extent;
                 Dgram* nonL1_dgram = (Dgram*)calloc(1, nonL1_dgram_size);
                 size_t memcpy_size =  sizeof(*smd_dgram) + smd_dgram->xtc.sizeofPayload();
                 printf("calloc size = %d, memcpy size = %d \n", nonL1_dgram_size, memcpy_size);
                 //copy header??
                 //From Smd::generate
                 memcpy(nonL1_dgram, smd_dgram, sizeof(*smd_dgram));
                 //copy payload
                 memcpy(nonL1_dgram->xtc.payload(), smd_dgram->xtc.payload(), smd_dgram->xtc.sizeofPayload());
                 assert(nonL1_dgram->time.value() == smd_dgram->time.value());
                 assert(0 == memcmp(nonL1_dgram->xtc.payload(), smd_dgram->xtc.payload(), smd_dgram->xtc.sizeofPayload()));
                 info.isL1 = 0;
                 info.ds_type = DS_NON_L1;
                 info.nonL1Dgram = (void*) nonL1_dgram;
                 printf("load_index: dgram_id = %llu, sizeofPayload = %d\n", info.dgram_id, smd_dgram->xtc.sizeofPayload());
             } else { //L1 events
                 info.isL1 = 1;
                 info.nonL1Dgram = NULL;
                 info.ds_type = DS_L1;
                 //info.dgram_size = smditer.dgramSize;
                 printf("load_index: dgram_id = %llu, dgram_offset = 0x%llx\n", info.dgram_id, info.dgram_offset);
             }
             (*index_map)[info.dgram_id] = info;
         }
         this->_index_map = index_map;
         return 0;
     }
References dgram_info::dgram_id, dgram_info::dgram_offset, DS_L1, DS_NON_L1, dgram_info::ds_type, dgram_info::isL1, dgram_info::nonL1Dgram, SmdIter::offset, and SmdIter::reset().
Referenced by iterate_list_all().
namesLookup()
NamesLookup* namesLookup () inline
Definition at line 896 of file xtc_io_api.cc.
{
         return &_namesLookup; //map
     }
pop_token()
void pop_token () inline
Definition at line 802 of file xtc_io_api.cc.
                     {
         _CURRENT_PATH_TOKENS.pop_back();
         _index_decrement();
     }
Referenced by iterate_list_all().
print_input_path()
void print_input_path () inline
Definition at line 806 of file xtc_io_api.cc.
{
         printf("input path = ");
         print_path(_INPUT_PATH_TOKENS);
     }
References print_path().
print_local_path()
void print_local_path (void) inline
Definition at line 810 of file xtc_io_api.cc.
{
         printf("current local");
         print_path(_CURRENT_PATH_TOKENS);
         printf("\n");
     }
References print_path().
process()
int process (Xtc * xtc) inline
This function is an implementation of Xtc::iterate() interface.
Definition at line 604 of file xtc_io_api.cc.
{
         int ret = -1;;
         switch(get_iterator_type()){
             case LIST_ALL:
                 ret = process_list_all(xtc);
                 break;
             default:
                 ret = -1;
                 break;
         }
         return ret;
     }
process_list_all()
int process_list_all (Xtc * xtc) inline
Currently the only scan type is to scan all to build the hierarchy.
Definition at line 620 of file xtc_io_api.cc.
     {
         assert(this->_current_dgram);
         uint64_t dgram_id = this->_current_dgram->time.value();
         xtc_dgram_info dgram_info;
         printf("%s:%d:  dbgiter = %p, this->_current_dgram = %p, dgram_id = 0x%llx\n",
                 __func__, __LINE__, this, this->_current_dgram, dgram_id);
         //Ensure the smd data is valid for the xtc2 file: all things here should have an entry in the index.
         if(find_index(dgram_id, &dgram_info) != 0)
             return -1;
         printf("dgram_id = 0x%llx, dgram_info.isL1 = %d, ds_type = %d\n", dgram_info.dgram_id, dgram_info.isL1, dgram_info.ds_type);
         switch (xtc->contains.id()) {
         case (TypeId::Parent): {
             printf("Found TypeID == Parent, iterating...\n");
             iterate(xtc);
             break;
         }
         case (TypeId::Names): {
             printf("=============================== find Names!!!\n");
             Names& names = *(Names*)xtc;
             _namesLookup[names.namesId()] = NameIndex(names);
             Alg& alg = names.alg();
             string token = names.detName();
             token += "_";
             token += names.detType();
             token += "_";
             token += alg.name();
             append_token(token);
             append_token(to_string(names.segment()));
             xtc_object* new_obj = xtc_obj_new(CURRENT_LOCATION, get_current_path().c_str());
             xtc_tree_node_add(new_xtc_node(new_obj));
             for (unsigned i = 0; i < names.num(); i++) {
                 Name& name = names.get(i);
                 append_token(name.name());
                 //print_local_path();
                 string path_str = get_current_path();
                 xtc_object* new_obj = xtc_obj_new(CURRENT_LOCATION, path_str.c_str());
                 xtc_tree_node_add(new_xtc_node(new_obj));
                 pop_token();
             }
             pop_token();//segment
             pop_token();//detName_detType_alg
             break;
         }
         case (TypeId::ShapesData): {
             printf("=============================== find ShapesData!!!\n");
             int shapesdata_offset = (char*)xtc - (char*)(this->_current_dgram);
             ShapesData* shapesdata = (ShapesData*)calloc(1, sizeof(ShapesData*));
             shapesdata = static_cast<ShapesData*>(xtc);//if sure it is such a subclass type
             NamesId namesId = shapesdata->namesId();
             if (_namesLookup.count(namesId)<=0) {
                 printf("*** Corrupt xtc: namesid 0x%x not found in NamesLookup\n",(int)namesId);
                 throw "invalid namesid";
                 break;
             }
             DescData descdata(*shapesdata, _namesLookup[namesId]);
             Names& names = descdata.nameindex().names();
             Data& data = shapesdata->data();
             string token = names.detName();
             token += "_";
             token += names.detType();
             token += "_";
             token += names.alg().name();
             append_token(token);
             append_token(to_string(names.segment()));
             string time_stamp_str = to_string(((Dgram*)CURRENT_LOCATION->dg)->time.asDouble());
             //check DS holder group existence.
             string cur_path = get_current_path();
             printf("search cur_path = %s\n", cur_path.c_str());
             xtc_node* group_ds_holder = xtc_tree_node_find(&cur_path); //the direct holder group of datasets
             if(!group_ds_holder){
                 printf("Create group_ds_holder: %s\n", cur_path.c_str());
                 xtc_object* new_obj = xtc_obj_new(CURRENT_LOCATION, get_current_path().c_str());
                 xtc_tree_node_add(new_xtc_node(new_obj));
             } //do nothing if group exists.
             //  Store time stamps in a virtual dataset
             cur_path += "/";
             cur_path += TIMESTAMP_DS_NAME;
             xtc_node* timestamp_ds_node = xtc_tree_node_find(&cur_path);
             double time_stamp = ((Dgram*)CURRENT_LOCATION->dg)->time.asDouble();
             if(!timestamp_ds_node){// create timestamp dataset
                 printf("Create timestamp_ds: %s\n", cur_path.c_str());
                 append_token(TIMESTAMP_DS_NAME);
                 xtc_object* new_obj = xtc_obj_new(CURRENT_LOCATION, get_current_path().c_str());
                 new_obj->obj_type = XTC_TIME_DS;//XTC_TIME_DS
                 vector<double>* tsv = new vector<double>();
                 tsv->push_back(time_stamp);
                 new_obj->data = (void*) tsv;
                 xtc_ds_info* ds_info = (xtc_ds_info*)calloc(1, sizeof(xtc_ds_info));
                 ds_info->current_dims[0] = 1;
                 ds_info->type = DOUBLE;
                 ds_info->element_cnt = 1;
                 ds_info->dim_cnt = 1; //1D array
                 ds_info->maximum_dims = NULL;
                 ds_info->isTimestampsDS = 1;
                 ds_info->ds_type = DS_TIMESTAMP;
                 new_obj->ds_info = ds_info;
                 new_obj->ds_info->data_handle = NULL;
                 xtc_tree_node_add(new_xtc_node(new_obj));
                 pop_token();//ds name
             } else {//add timestamp to dataset
                 assert(timestamp_ds_node->my_obj);
                 assert(timestamp_ds_node->my_obj->data);
                 ((vector<double>*)(timestamp_ds_node->my_obj->data))->push_back(time_stamp);
                 timestamp_ds_node->my_obj->ds_info->element_cnt =
                         ((vector<double>*)(timestamp_ds_node->my_obj->data))->size();
             }
             for (unsigned i = 0; i < names.num(); i++) {
                 Name& name = names.get(i);
                 if (strcmp(name.name(),"intOffset")==0) {
                     uint64_t offset = descdata.get_value<uint64_t>(i);
                     //printf("Type=ShapesData  offset = 0x%x\n", offset);
                 }
                 append_token(name.name());//ds name
                 print_local_path();
                 string path_str = get_current_path();
                 xtc_object* new_obj = xtc_obj_new(CURRENT_LOCATION, get_current_path().c_str());
                 new_obj->obj_type = XTC_DS;
                 //For both L1 and non-L1 datasets
                 dgram_info.shapesdata_offset = shapesdata_offset;
                 new_obj->ds_info = get_ds_info(i, shapesdata, dgram_info);
                 xtc_tree_node_add(new_xtc_node(new_obj));
                 get_value(i, name, descdata);
                 pop_token();//ds name
             }
         pop_token();//segment
         pop_token();//detName_detType_alg
             break;
         }
         default:
             break;
         }
         return Continue;
     }
References XTC_DS_info::current_dims, XTC_C_API_HELPER::data, XTC_DS_info::data_handle, dgram_info::dgram_id, XTC_DS_info::dim_cnt, DOUBLE, XTC_C_API_HELPER::ds_info, DS_TIMESTAMP, dgram_info::ds_type, XTC_DS_info::ds_type, XTC_DS_info::element_cnt, dgram_info::isL1, XTC_DS_info::isTimestampsDS, XTC_DS_info::maximum_dims, XTC_Tree_Node::my_obj, new_xtc_node(), XTC_C_API_HELPER::obj_type, dgram_info::shapesdata_offset, TIMESTAMP_DS_NAME, XTC_DS_info::type, XTC_DS, xtc_obj_new(), and XTC_TIME_DS.
set_current_dgram()
void set_current_dgram (Dgram * dgram) inline
Definition at line 900 of file xtc_io_api.cc.
{
         assert(dgram);
         this->_current_dgram = dgram;
         printf("set_current_dgram: resulting id = %llu\n", this->_current_dgram->time.value());
     }
set_input_path()
void set_input_path (vector< string > str_vec) inline
Definition at line 785 of file xtc_io_api.cc.
{
         _INPUT_PATH_TOKENS = str_vec;
     }
set_iterator_type()
void set_iterator_type (ItType type) inline
Definition at line 835 of file xtc_io_api.cc.
{
         iterator_type = type;
     }
Referenced by iterate_list_all().
xtc_tree_init() [1/2]
void xtc_tree_init (xtc_object * root_obj) inline
The tree-related functions below are used to build and access the metadata index tree, in which each node represents a path and a location in the HDF5 virtual file hierarchy.
Definition at line 849 of file xtc_io_api.cc.
{
         ROOT_NODE = new_xtc_node(root_obj);
         ROOT_NODE->parent = NULL;
         (*root_obj).tree_node = (void*)ROOT_NODE;
     }
References new_xtc_node().
Referenced by iterate_list_all().
xtc_tree_init() [2/2]
void xtc_tree_init (int fd) inline
Definition at line 854 of file xtc_io_api.cc.
{
         xtc_object* root_obj = (xtc_object*)calloc(1, sizeof(xtc_object));
         root_obj->fd = fd;
         root_obj->obj_path_abs = strdup("/");
         xtc_h5token_new((xtc_token_t**)&(root_obj->obj_token), 16);
         ROOT_NODE = new_xtc_node(root_obj);
         ROOT_NODE->parent = NULL;
     }
References XTC_C_API_HELPER::fd, new_xtc_node(), XTC_C_API_HELPER::obj_path_abs, XTC_C_API_HELPER::obj_token, and xtc_h5token_new().
xtc_tree_node_add()
int xtc_tree_node_add (xtc_node * node) inline
Definition at line 863 of file xtc_io_api.cc.
{
         return add_xtc_node(ROOT_NODE, node);
     }
References add_xtc_node().
Referenced by iterate_list_all().
xtc_tree_node_find() [1/2]
xtc_node* xtc_tree_node_find (const char * target_path) inline
Definition at line 867 of file xtc_io_api.cc.
{
         return find_xtc_node(ROOT_NODE, target_path);
     }
References find_xtc_node().
xtc_tree_node_find() [2/2]
xtc_node* xtc_tree_node_find (string * target_path_in) inline
Definition at line 870 of file xtc_io_api.cc.
{
         return xtc_tree_node_find(target_path_in->c_str());
     }
xtc_tree_print()
int xtc_tree_print () inline
Definition at line 876 of file xtc_io_api.cc.
{
         return print_tree(ROOT_NODE);
     }
References print_tree().
Referenced by iterate_list_all().
Field Documentation
_current_dgram
Dgram* _current_dgram
Definition at line 1042 of file xtc_io_api.cc.
Referenced by iterate_list_all().
_CURRENT_PATH_TOKENS
vector<string> _CURRENT_PATH_TOKENS
Definition at line 895 of file xtc_io_api.cc.
_INPUT_PATH_TOKENS
vector<string> _INPUT_PATH_TOKENS
Definition at line 843 of file xtc_io_api.cc.
CURRENT_LOCATION
xtc_location* CURRENT_LOCATION
Definition at line 894 of file xtc_io_api.cc.
Referenced by iterate_list_all().
SCAN_DEPTH
int SCAN_DEPTH
Definition at line 826 of file xtc_io_api.cc.
The documentation for this class was generated from the following file:
xtc_io_api.cc