XTC_VOL: xtc_io_api_c.h File Reference
xtc_io_api_c.h File Reference
This file defines the interface and shared data structures between XTC2 iterator (C++) and HDF5 VOL (C).
#include <stdint.h>
Data Structures
struct XTC_token
struct Xtc_Location
struct dgram_info
struct Xtc_dataset_handle
struct XTC_DS_info
struct XTC_C_API_HELPER
Macros
#define EXTERNC
#define PATH_LEN_MAX 100
Typedefs
typedef void * xtc_func_t
typedef enum XTC_Data_type xtc_data_type
typedef enum XTC_Object_type xtc_object_type_t
typedef enum EXECUTION_RETURN exec_ret
typedef struct XTC_token xtc_token_t
typedef unsigned long long h5_size_t
typedef struct Xtc_Location xtc_location
typedef enum Dataset_TYPE ds_type
typedef struct dgram_info xtc_dgram_info
typedef struct Xtc_dataset_handle xtc_data_handle
typedef struct XTC_DS_info xtc_ds_info
typedef struct XTC_C_API_HELPER xtc_object
Enumerations
enum XTC_Data_type {
UINT8, UINT16, UINT32, UINT64,
INT8, INT16, INT32, INT64,
FLOAT, DOUBLE, CHARSTR, ENUMVAL,
ENUMDICT
}
enum XTC_Object_type {
XTC_FILE, XTC_HEAD, XTC_GROUP, XTC_DS,
XTC_TIME_DS, XTC_LEAVE
}
enum EXECUTION_RETURN { SUCCESS, NOT_FOUND, RESERVED_1 }
enum Dataset_TYPE { DS_TIMESTAMP, DS_NON_L1, DS_L1 }
Functions
unsigned long xtc_h5token_new (xtc_token_t **token_in_out, unsigned int h5_token_size)
xtc_object * xtc_file_open (const char *path)
xtc_func_t xtc_it_open (void *param)
void xtc_file_close (xtc_object *helper)
size_t dataset_read_all (xtc_object *obj, void *buf_out)
xtc_object * xtc_obj_find (xtc_object *obj, const char *path)
xtc_object ** xtc_get_children_list (xtc_object *group, int *num_out)
void extern_test_root (xtc_object *root_obj)
Detailed Description
This file defines the interface and shared data structures between XTC2 iterator (C++) and HDF5 VOL (C).
Created on: Jan 20, 2020 Author: tonglin
Definition in file xtc_io_api_c.h.
Macro Definition Documentation
EXTERNC
#define EXTERNC
Definition at line 16 of file xtc_io_api_c.h.
PATH_LEN_MAX
#define PATH_LEN_MAX 100
Definition at line 19 of file xtc_io_api_c.h.
Typedef Documentation
ds_type
typedef enum Dataset_TYPE ds_type
exec_ret
typedef enum EXECUTION_RETURN exec_ret
h5_size_t
typedef unsigned long long h5_size_t
Definition at line 53 of file xtc_io_api_c.h.
xtc_data_handle
typedef struct Xtc_dataset_handle xtc_data_handle
xtc_data_type
typedef enum XTC_Data_type xtc_data_type
xtc_dgram_info
typedef struct dgram_info xtc_dgram_info
xtc_ds_info
typedef struct XTC_DS_info xtc_ds_info
xtc_func_t
typedef void* xtc_func_t
Definition at line 21 of file xtc_io_api_c.h.
xtc_location
typedef struct Xtc_Location xtc_location
xtc_object
typedef struct XTC_C_API_HELPER xtc_object
xtc_object_type_t
typedef enum XTC_Object_type xtc_object_type_t
xtc_token_t
typedef struct XTC_token xtc_token_t
Enumeration Type Documentation
Dataset_TYPE
enum Dataset_TYPE
Enumerator
DS_TIMESTAMP
DS_NON_L1
DS_L1
Definition at line 63 of file xtc_io_api_c.h.
{
     DS_TIMESTAMP,
     DS_NON_L1,
     DS_L1
 }ds_type;
EXECUTION_RETURN
enum EXECUTION_RETURN
Enumerator
SUCCESS
NOT_FOUND
RESERVED_1
Definition at line 42 of file xtc_io_api_c.h.
{
     SUCCESS,
     NOT_FOUND,
     RESERVED_1
 }exec_ret;
XTC_Data_type
enum XTC_Data_type
Enumerator
UINT8
UINT16
UINT32
UINT64
INT8
INT16
INT32
INT64
FLOAT
DOUBLE
CHARSTR
ENUMVAL
ENUMDICT
Definition at line 25 of file xtc_io_api_c.h.
{
     UINT8, UINT16, UINT32, UINT64,
     INT8, INT16, INT32, INT64,
     FLOAT, DOUBLE,
     CHARSTR,
     ENUMVAL, ENUMDICT
 }xtc_data_type;
XTC_Object_type
enum XTC_Object_type
Enumerator
XTC_FILE
XTC_HEAD
XTC_GROUP
XTC_DS
XTC_TIME_DS
XTC_LEAVE
Definition at line 33 of file xtc_io_api_c.h.
{
     XTC_FILE,
     XTC_HEAD,//root group
     XTC_GROUP,
     XTC_DS,
     XTC_TIME_DS, // virtual dataset for time stamps
     XTC_LEAVE,
 }xtc_object_type_t;
Function Documentation
dataset_read_all()
size_t dataset_read_all (xtc_object * obj, void * buf_out)
Read and return the whole dataset for HDF5 dataset_read() call.
Definition at line 1068 of file xtc_io_api.cc.
{
     size_t read_size = 0;
     assert(obj->location && obj->ds_info &&
             (obj->obj_type == XTC_DS || obj->obj_type == XTC_TIME_DS));
     assert(obj->location->dbgiter);
     assert(obj->ds_info);
     DebugIter* dbgit = (DebugIter*)(obj->location->dbgiter);
     if(obj->ds_info->ds_type == DS_TIMESTAMP){//timestamps dataset
         vector<double>* time_stamps_ds = (vector<double>*) obj->data;
         read_size = time_stamps_ds->size()* sizeof(double);
         for(int i = 0; i < time_stamps_ds->size(); i++){
             double ts = time_stamps_ds->at(i);
             memcpy((char*)buf_out + (i * sizeof(double)), &ts, sizeof(double));
             printf("dataset_read_all: timestamp = %lf\n", ts);
         }
     } else if(obj->ds_info->ds_type == DS_NON_L1){//read from in-memory non-L1 dgrams.
 //        printf("%s:%d: obj->ds_info->ds_type = %d, dgram_info->ds_type = %d, dgram_info->nonL1Dgram = %p\n",
 //                __func__, __LINE__, obj->ds_info->ds_type, obj->ds_info->data_handle->dgram_info->ds_type, obj->ds_info->data_handle->dgram_info->nonL1Dgram);
         read_size = dbgit->get_data(obj, obj->ds_info->total_pixel_cnt, buf_out);
     } else if(obj->ds_info->ds_type == DS_L1){//regular xtc2 dataset
 //        printf("%s:%d: obj->ds_info->ds_type = %d, obj->ds_info->data_handle->dgram_info->ds_type = %d\n",
 //                __func__, __LINE__, obj->ds_info->ds_type, obj->ds_info->data_handle->dgram_info->ds_type);
         Xtc* xtc = (Xtc*)(obj->ds_info->data_handle->xtc_ptr);
         size_t read_size = dbgit->get_data(obj, obj->ds_info->total_pixel_cnt, buf_out);
         printf("data = [%s], data = %p, read_size = %d\n", (char*)(buf_out), buf_out, read_size);
     } else {
         printf("Unsupported ds_type: %d\n", obj->ds_info->ds_type);
         return -1;
     }
     DEBUG_PRINT
     return read_size;
 }
References XTC_C_API_HELPER::data, XTC_DS_info::data_handle, Xtc_Location::dbgiter, DEBUG_PRINT, XTC_C_API_HELPER::ds_info, DS_L1, DS_NON_L1, DS_TIMESTAMP, XTC_DS_info::ds_type, DebugIter::get_data(), XTC_C_API_HELPER::location, XTC_C_API_HELPER::obj_type, XTC_DS_info::total_pixel_cnt, XTC_DS, Xtc_dataset_handle::xtc_ptr, and XTC_TIME_DS.
extern_test_root()
void extern_test_root (xtc_object * root_obj)
Definition at line 1267 of file xtc_io_api.cc.
{
     assert(root_obj);
     assert(root_obj->location);
     printf("%s:%d:  xtc_obj = %p, dbg = %p, dbg->get_root() = %p\n",
             __func__, __LINE__, root_obj, root_obj->location->dbgiter,
             ((DebugIter*)(root_obj->location->dbgiter))->get_root());
 }
References Xtc_Location::dbgiter, and XTC_C_API_HELPER::location.
Referenced by cc_extern_test_root().
xtc_file_close()
void xtc_file_close (xtc_object * helper)
Definition at line 1307 of file xtc_io_api.cc.
{
     assert(head);
     //assert(head->location);
 //    if(head->location->dbgiter){
 //        DebugIter* dbgiter = (DebugIter*) head->location->dbgiter;
 //        if(dbgiter)
 //            delete dbgiter;
 //    }
 //    if(head->location->dg){
 //        Dgram* dg = (Dgram*) head->location->dg;
 //        if(dg)
 //            delete dg;
 //    }
     close(head->fd);
     //delete helper->dbgiter;
     //delete (Dgram*)(helper->target_it);
 //    free(helper);
 }
References XTC_C_API_HELPER::fd.
xtc_file_open()
xtc_object* xtc_file_open (const char * path)
Definition at line 1292 of file xtc_io_api.cc.
{
     int fd = open(file_path, O_RDONLY);//open xtc2 file
     string fname = string(file_path);
     vector<string> tokens = str_tok(file_path, ".");
     assert(tokens.size() == 2 && tokens[1].compare("xtc2") == 0);
     string smd_fname(tokens[0]);
     smd_fname += ".smd";
     smd_fname += ".xtc2";
     int index_fd = open(smd_fname.c_str(), O_RDONLY);//open smd file
     printf("fd = %d, index_fd = %d\n", fd, index_fd);
     xtc_object* head_obj = iterate_list_all(fd, index_fd);
     return head_obj;//contains a pointer to root node.
 }
References iterate_list_all(), and str_tok().
xtc_get_children_list()
xtc_object** xtc_get_children_list (xtc_object * group, int * num_out)
Definition at line 1327 of file xtc_io_api.cc.
{
     return get_children_obj(group_in, num_out);//NULL if no children
 }
References get_children_obj().
Referenced by loop_children().
xtc_h5token_new()
unsigned long xtc_h5token_new (xtc_token_t ** token_in_out, unsigned int h5_token_size)
Definition at line 1245 of file xtc_io_api.cc.
{
     if(!*token)
         *token = (xtc_token_t*)calloc(1, sizeof(xtc_token_t));
     struct timeval tp;
     gettimeofday(&tp, NULL);
     int32_t tval = (int32_t)((1000000 * tp.tv_sec) + tp.tv_usec);
     int n = sizeof(int32_t)/sizeof(uint8_t);
     for(int i = 0; i < h5_token_size; i++){//16
         if(i < n)
             (*token)->__data[i] = *(uint8_t*)(&tval + i * sizeof(uint8_t));
         else
             (*token)->__data[i] = 0;
     }
     return tval;
 }
Referenced by new_virtual_xtc_node(), new_xtc_h5token(), xtc_obj_new(), and DebugIter::xtc_tree_init().
xtc_it_open()
xtc_func_t xtc_it_open (void * param)
xtc_obj_find()
xtc_object* xtc_obj_find (xtc_object * obj, const char * path)
Definition at line 1275 of file xtc_io_api.cc.
{
     assert(root_obj && path);
     assert(root_obj->location);
     if(strcmp(path, "/") == 0){
         return root_obj;
     }
     assert(((DebugIter*)(root_obj->location->dbgiter))->get_root());
     xtc_node* node = ((DebugIter*)(root_obj->location->dbgiter))->xtc_tree_node_find(path);
     if(node)
         return node->my_obj;
     else
         return NULL;
 }
References Xtc_Location::dbgiter, XTC_C_API_HELPER::location, and XTC_Tree_Node::my_obj.
Referenced by _internal_obj_lookup_by_name().