XTC_VOL: xtc_io_api_cpp.hh File Reference
xtc_io_api_cpp.hh File Reference
Internal utility functions in C++ for XTC iterator. Created on: Feb 16, 2020 Author: tonglin.
#include <string>
#include <vector>
Functions
vector< string > str_tok (const char *str, const char *delimiters_str)
string tok_to_str (vector< string > token_list)
void print_path (vector< string >vec)
void cc_extern_test_root (void *root_obj)
Detailed Description
Internal utility functions in C++ for XTC iterator. Created on: Feb 16, 2020 Author: tonglin.
Definition in file xtc_io_api_cpp.hh.
Function Documentation
cc_extern_test_root()
void cc_extern_test_root (void * root_obj)
Definition at line 1262 of file xtc_io_api.cc.
{
     DEBUG_PRINT
     return extern_test_root((xtc_object*)root_obj);
 }
References DEBUG_PRINT, and extern_test_root().
print_path()
void print_path (vector< string > vec)
Definition at line 1110 of file xtc_io_api.cc.
 {
     if(vec.size()==0)
         return;
     printf(" path = ");
     for(vector<string>::iterator it = vec.begin(); it != vec.end(); ++it){
         printf("/%s", (*it).c_str());
     }
 }
Referenced by DebugIter::print_input_path(), and DebugIter::print_local_path().
str_tok()
vector<string> str_tok (const char * str, const char * delimiters_str)
Definition at line 1120 of file xtc_io_api.cc.
{
     assert(str && delimiters_str);
     char* str_mod = strdup(str);
     vector<string> res;
     char * pch;
     pch = strtok(str_mod, delimiters_str);
     while (pch != NULL){
       res.push_back(string(pch));
       pch = strtok (NULL, delimiters_str);
     }
     free(str_mod);
     return res;
 }
Referenced by find_xtc_node(), new_xtc_node(), and test_str_tok().
tok_to_str()
string tok_to_str (vector< string > token_list)
Definition at line 1134 of file xtc_io_api.cc.
{
     string s("/");
     for(auto i : token_list){
         s += i;
         if(i != token_list.back())
             s += "/";
     }
     return s;
 }
Referenced by new_virtual_xtc_node(), and print_tree_node().