XTC_VOL: xtc_io_api.cc File Reference
xtc_io_api.cc File Reference
XTC2 iterator and utility functions, used to scan xtc2 file and smd file to load the metadata and to build the index tree.
#include <fcntl.h>
#include <map>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <cstring>
#include <unistd.h>
#include <unordered_map>
#include <xtcdata/xtc/XtcFileIterator.hh>
#include <xtcdata/xtc/XtcIterator.hh>
#include <xtcdata/xtc/ShapesData.hh>
#include <xtcdata/xtc/DescData.hh>
#include <vector>
#include <sys/time.h>
#include "xtc_io_api_c.h"
#include "xtc_io_api_cpp.hh"
#include "xtc_tree.hh"
Data Structures
class SmdIter
class DebugIter
Macros
#define TIMESTAMP_DS_NAME "timestamps"
#define DEBUG_PRINT printf("%s():%d\n", __func__, __LINE__);
Functions
char * name_convert (const char *h5_name)
int check_update_dgram (int fd, xtc_dgram_info *dg_info, Dgram *current_dgram_in_out)
xtc_object * xtc_obj_new (int fd, void *fileIter, void *dbgiter, void *dg, const char *obj_path_abs)
xtc_object * xtc_obj_new (xtc_location *location, const char *obj_path_abs)
size_t dataset_read_all (xtc_object *obj, void *buf_out)
void print_path (vector< string >vec)
vector< string > str_tok (const char *str, const char *delimiters_str)
string tok_to_str (vector< string > token_list)
void test_str_tok ()
int verifyDgram (Dgram *dgram)
xtc_object * iterate_list_all (int fd, int index_fd)
unsigned long xtc_h5token_new (xtc_token_t **token, unsigned int h5_token_size)
void cc_extern_test_root (void *root_obj)
void extern_test_root (xtc_object *root_obj)
xtc_object * xtc_obj_find (xtc_object *root_obj, const char *path)
xtc_object * xtc_file_open (const char *file_path)
void xtc_file_close (xtc_object *head)
xtc_object ** xtc_get_children_list (xtc_object *group_in, int *num_out)
Detailed Description
XTC2 iterator and utility functions, used to scan xtc2 file and smd file to load the metadata and to build the index tree.
Definition in file xtc_io_api.cc.
Macro Definition Documentation
DEBUG_PRINT
#define DEBUG_PRINT printf("%s():%d\n", __func__, __LINE__);
Definition at line 32 of file xtc_io_api.cc.
TIMESTAMP_DS_NAME
#define TIMESTAMP_DS_NAME "timestamps"
Definition at line 31 of file xtc_io_api.cc.
Function Documentation
cc_extern_test_root()
void cc_extern_test_root (void * root_obj)
Definition at line 1262 of file xtc_io_api.cc.
{
     DEBUG_PRINT
     return extern_test_root((xtc_object*)root_obj);
 }
References DEBUG_PRINT, and extern_test_root().
check_update_dgram()
int check_update_dgram (int fd, xtc_dgram_info * dg_info, Dgram * current_dgram_in_out)
Referenced by DebugIter::get_data().
dataset_read_all()
size_t dataset_read_all (xtc_object * obj, void * buf_out)
Read and return the whole dataset for HDF5 dataset_read() call.
Definition at line 1068 of file xtc_io_api.cc.
{
     size_t read_size = 0;
     assert(obj->location && obj->ds_info &&
             (obj->obj_type == XTC_DS || obj->obj_type == XTC_TIME_DS));
     assert(obj->location->dbgiter);
     assert(obj->ds_info);
     DebugIter* dbgit = (DebugIter*)(obj->location->dbgiter);
     if(obj->ds_info->ds_type == DS_TIMESTAMP){//timestamps dataset
         vector<double>* time_stamps_ds = (vector<double>*) obj->data;
         read_size = time_stamps_ds->size()* sizeof(double);
         for(int i = 0; i < time_stamps_ds->size(); i++){
             double ts = time_stamps_ds->at(i);
             memcpy((char*)buf_out + (i * sizeof(double)), &ts, sizeof(double));
             printf("dataset_read_all: timestamp = %lf\n", ts);
         }
     } else if(obj->ds_info->ds_type == DS_NON_L1){//read from in-memory non-L1 dgrams.
 //        printf("%s:%d: obj->ds_info->ds_type = %d, dgram_info->ds_type = %d, dgram_info->nonL1Dgram = %p\n",
 //                __func__, __LINE__, obj->ds_info->ds_type, obj->ds_info->data_handle->dgram_info->ds_type, obj->ds_info->data_handle->dgram_info->nonL1Dgram);
         read_size = dbgit->get_data(obj, obj->ds_info->total_pixel_cnt, buf_out);
     } else if(obj->ds_info->ds_type == DS_L1){//regular xtc2 dataset
 //        printf("%s:%d: obj->ds_info->ds_type = %d, obj->ds_info->data_handle->dgram_info->ds_type = %d\n",
 //                __func__, __LINE__, obj->ds_info->ds_type, obj->ds_info->data_handle->dgram_info->ds_type);
         Xtc* xtc = (Xtc*)(obj->ds_info->data_handle->xtc_ptr);
         size_t read_size = dbgit->get_data(obj, obj->ds_info->total_pixel_cnt, buf_out);
         printf("data = [%s], data = %p, read_size = %d\n", (char*)(buf_out), buf_out, read_size);
     } else {
         printf("Unsupported ds_type: %d\n", obj->ds_info->ds_type);
         return -1;
     }
     DEBUG_PRINT
     return read_size;
 }
References XTC_C_API_HELPER::data, XTC_DS_info::data_handle, Xtc_Location::dbgiter, DEBUG_PRINT, XTC_C_API_HELPER::ds_info, DS_L1, DS_NON_L1, DS_TIMESTAMP, XTC_DS_info::ds_type, DebugIter::get_data(), XTC_C_API_HELPER::location, XTC_C_API_HELPER::obj_type, XTC_DS_info::total_pixel_cnt, XTC_DS, Xtc_dataset_handle::xtc_ptr, and XTC_TIME_DS.
extern_test_root()
void extern_test_root (xtc_object * root_obj)
Definition at line 1267 of file xtc_io_api.cc.
{
     assert(root_obj);
     assert(root_obj->location);
     printf("%s:%d:  xtc_obj = %p, dbg = %p, dbg->get_root() = %p\n",
             __func__, __LINE__, root_obj, root_obj->location->dbgiter,
             ((DebugIter*)(root_obj->location->dbgiter))->get_root());
 }
References Xtc_Location::dbgiter, and XTC_C_API_HELPER::location.
Referenced by cc_extern_test_root().
iterate_list_all()
xtc_object* iterate_list_all (int fd, int index_fd)
The entry point of iterating the xtc2 file, it read the file, build metadata index tree and dgram index map for later faster access.
Definition at line 1162 of file xtc_io_api.cc.
{
     static const unsigned bigdgBufferSize = 0x4000000;
     XtcFileIterator* iter = new XtcFileIterator(fd, bigdgBufferSize);
     DebugIter* dbgiter = new DebugIter();
     bool debugprint = true;
     dbgiter->load_index(index_fd);
     dbgiter->_current_dgram = (Dgram*)malloc(bigdgBufferSize);
     //location init
     dbgiter->CURRENT_LOCATION = (xtc_location*)calloc(1, sizeof(xtc_location));
     dbgiter->CURRENT_LOCATION->fd = fd;
     dbgiter->CURRENT_LOCATION->fileIter = (void*)(iter);
     dbgiter->CURRENT_LOCATION->dbgiter = (void*)(dbgiter);
     dbgiter->CURRENT_LOCATION->dg = NULL;
     dbgiter->index_init();//-1
     dbgiter->set_iterator_type(DebugIter::LIST_ALL);
     dbgiter->_current_dgram = iter->next();//first dg, for configure transition.
     dbgiter->CURRENT_LOCATION->dg = (void*) dbgiter->_current_dgram;
     xtc_object* head_obj = xtc_obj_new(fd, iter, dbgiter, dbgiter->_current_dgram, "/");
     head_obj->obj_type = XTC_HEAD;
     dbgiter->xtc_tree_init(head_obj);
     string candidate_str = string(TransitionId::name(dbgiter->_current_dgram->service()));
     dbgiter->append_token(candidate_str);
     dbgiter->iterate(&(dbgiter->_current_dgram->xtc));
     dbgiter->pop_token();
     int L1accept_cnt = 0;
     bool isConfigureTransition = true;
     while (dbgiter->_current_dgram = iter->next()) {//each data item in the file
         string candidate_str = string(TransitionId::name(dbgiter->_current_dgram->service()));
         dbgiter->append_token(candidate_str);
         xtc_object* xtc_obj = xtc_obj_new(fd, iter, dbgiter, dbgiter->_current_dgram, dbgiter->get_current_path().c_str());
         dbgiter->xtc_tree_node_add(new_xtc_node(xtc_obj));
         DEBUG_PRINT
         Xtc* xtc = &(dbgiter->_current_dgram->xtc);
         if (debugprint) {
             ShapesData& shapesdata = *(ShapesData*)xtc;
             printf("iterate_list_all(): xtc = %p, shapesdata = %p\n", xtc, &shapesdata);
             dbgiter->iterate(xtc);
         }
         dbgiter->pop_token();
     }
     printf("\n\n\n\n");
     dbgiter->xtc_tree_print();
     printf("\n\n\n\n");
     return head_obj;
 }
References DebugIter::_current_dgram, DebugIter::append_token(), DebugIter::CURRENT_LOCATION, Xtc_Location::dbgiter, DEBUG_PRINT, Xtc_Location::dg, Xtc_Location::fd, Xtc_Location::fileIter, DebugIter::get_current_path(), DebugIter::index_init(), DebugIter::LIST_ALL, DebugIter::load_index(), new_xtc_node(), XTC_C_API_HELPER::obj_type, DebugIter::pop_token(), DebugIter::set_iterator_type(), XTC_HEAD, xtc_obj_new(), DebugIter::xtc_tree_init(), DebugIter::xtc_tree_node_add(), and DebugIter::xtc_tree_print().
Referenced by xtc_file_open().
name_convert()
char* name_convert (const char * h5_name)
Definition at line 35 of file xtc_io_api.cc.
{
     char* xtc_name_surfix;
     return xtc_name_surfix;
 }
print_path()
void print_path (vector< string > vec)
Definition at line 1110 of file xtc_io_api.cc.
 {
     if(vec.size()==0)
         return;
     printf(" path = ");
     for(vector<string>::iterator it = vec.begin(); it != vec.end(); ++it){
         printf("/%s", (*it).c_str());
     }
 }
Referenced by DebugIter::print_input_path(), and DebugIter::print_local_path().
str_tok()
vector<string> str_tok (const char * str, const char * delimiters_str)
Definition at line 1120 of file xtc_io_api.cc.
{
     assert(str && delimiters_str);
     char* str_mod = strdup(str);
     vector<string> res;
     char * pch;
     pch = strtok(str_mod, delimiters_str);
     while (pch != NULL){
       res.push_back(string(pch));
       pch = strtok (NULL, delimiters_str);
     }
     free(str_mod);
     return res;
 }
Referenced by find_xtc_node(), new_xtc_node(), test_str_tok(), and xtc_file_open().
test_str_tok()
void test_str_tok ()
Definition at line 1143 of file xtc_io_api.cc.
                    {
     char sample[] = "this is a sample string, contains/multiple.delimiters. End.";
     vector<string> v = str_tok(sample, " ,/.");
     int n = v.size();
     for(int i = 0; i < n; i++){
         cout<< v[i] << endl;
     }
 }
References str_tok().
tok_to_str()
string tok_to_str (vector< string > token_list)
Definition at line 1134 of file xtc_io_api.cc.
{
     string s("/");
     for(auto i : token_list){
         s += i;
         if(i != token_list.back())
             s += "/";
     }
     return s;
 }
Referenced by new_virtual_xtc_node(), and print_tree_node().
verifyDgram()
int verifyDgram (Dgram * dgram)
Definition at line 1153 of file xtc_io_api.cc.
{
     return -1;
 }
xtc_file_close()
void xtc_file_close (xtc_object * head)
Definition at line 1307 of file xtc_io_api.cc.
{
     assert(head);
     //assert(head->location);
 //    if(head->location->dbgiter){
 //        DebugIter* dbgiter = (DebugIter*) head->location->dbgiter;
 //        if(dbgiter)
 //            delete dbgiter;
 //    }
 //    if(head->location->dg){
 //        Dgram* dg = (Dgram*) head->location->dg;
 //        if(dg)
 //            delete dg;
 //    }
     close(head->fd);
     //delete helper->dbgiter;
     //delete (Dgram*)(helper->target_it);
 //    free(helper);
 }
References XTC_C_API_HELPER::fd.
xtc_file_open()
xtc_object* xtc_file_open (const char * file_path)
Definition at line 1292 of file xtc_io_api.cc.
{
     int fd = open(file_path, O_RDONLY);//open xtc2 file
     string fname = string(file_path);
     vector<string> tokens = str_tok(file_path, ".");
     assert(tokens.size() == 2 && tokens[1].compare("xtc2") == 0);
     string smd_fname(tokens[0]);
     smd_fname += ".smd";
     smd_fname += ".xtc2";
     int index_fd = open(smd_fname.c_str(), O_RDONLY);//open smd file
     printf("fd = %d, index_fd = %d\n", fd, index_fd);
     xtc_object* head_obj = iterate_list_all(fd, index_fd);
     return head_obj;//contains a pointer to root node.
 }
References iterate_list_all(), and str_tok().
xtc_get_children_list()
xtc_object** xtc_get_children_list (xtc_object * group_in, int * num_out)
Definition at line 1327 of file xtc_io_api.cc.
{
     return get_children_obj(group_in, num_out);//NULL if no children
 }
References get_children_obj().
Referenced by loop_children().
xtc_h5token_new()
unsigned long xtc_h5token_new (xtc_token_t ** token, unsigned int h5_token_size)
Definition at line 1245 of file xtc_io_api.cc.
{
     if(!*token)
         *token = (xtc_token_t*)calloc(1, sizeof(xtc_token_t));
     struct timeval tp;
     gettimeofday(&tp, NULL);
     int32_t tval = (int32_t)((1000000 * tp.tv_sec) + tp.tv_usec);
     int n = sizeof(int32_t)/sizeof(uint8_t);
     for(int i = 0; i < h5_token_size; i++){//16
         if(i < n)
             (*token)->__data[i] = *(uint8_t*)(&tval + i * sizeof(uint8_t));
         else
             (*token)->__data[i] = 0;
     }
     return tval;
 }
Referenced by new_virtual_xtc_node(), new_xtc_h5token(), xtc_obj_new(), and DebugIter::xtc_tree_init().
xtc_obj_find()
xtc_object* xtc_obj_find (xtc_object * root_obj, const char * path)
Definition at line 1275 of file xtc_io_api.cc.
{
     assert(root_obj && path);
     assert(root_obj->location);
     if(strcmp(path, "/") == 0){
         return root_obj;
     }
     assert(((DebugIter*)(root_obj->location->dbgiter))->get_root());
     xtc_node* node = ((DebugIter*)(root_obj->location->dbgiter))->xtc_tree_node_find(path);
     if(node)
         return node->my_obj;
     else
         return NULL;
 }
References Xtc_Location::dbgiter, XTC_C_API_HELPER::location, and XTC_Tree_Node::my_obj.
Referenced by _internal_obj_lookup_by_name().
xtc_obj_new() [1/2]
xtc_object * xtc_obj_new (int fd, void * fileIter, void * dbgiter, void * dg, const char * obj_path_abs)
Definition at line 1221 of file xtc_io_api.cc.
{
     xtc_object* ret = (xtc_object*)calloc(1, sizeof(xtc_object));
     ret->fd = fd;
     ret->location = (xtc_location*) calloc(1, sizeof(xtc_location));
     ret->location->fd = fd;
     ret->location->dg = dg;
     ret->location->dbgiter = dbgiter;
     ret->location->fileIter = fileIter;
     ret->obj_type = XTC_GROUP;
     ret->obj_token = calloc(1, sizeof(xtc_token_t));
     ret->obj_path_abs = strdup(obj_path_abs);
     xtc_h5token_new((xtc_token_t**)&(ret->obj_token), 16);
     return ret;
 }
References Xtc_Location::dbgiter, Xtc_Location::dg, Xtc_Location::fd, XTC_C_API_HELPER::fd, Xtc_Location::fileIter, XTC_C_API_HELPER::location, XTC_C_API_HELPER::obj_path_abs, XTC_C_API_HELPER::obj_token, XTC_C_API_HELPER::obj_type, XTC_GROUP, and xtc_h5token_new().
Referenced by iterate_list_all(), DebugIter::process_list_all(), and xtc_obj_new().
xtc_obj_new() [2/2]
xtc_object * xtc_obj_new (xtc_location * location, const char * obj_path_abs)
Definition at line 1238 of file xtc_io_api.cc.
{
     assert(location);
     xtc_object* obj = xtc_obj_new(location->fd,
             location->fileIter, location->dbgiter, location->dg, obj_path_abs);
     return obj;
 }
References Xtc_Location::dbgiter, Xtc_Location::dg, Xtc_Location::fd, Xtc_Location::fileIter, and xtc_obj_new().