XTC_VOL: xtc_vol.c File Reference
xtc_vol.c File Reference
The actual XTC_VOL connector implementation.
#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <hdf5.h>
#include "xtc_vol.h"
#include "xtc_io_api_c.h"
Data Structures
struct H5VL_xtc_t
struct H5VL_xtc_wrap_ctx_t
Macros
#define DEBUG_PRINT
Typedefs
typedef struct H5VL_xtc_t H5VL_xtc_t
typedef struct H5VL_xtc_wrap_ctx_t H5VL_xtc_wrap_ctx_t
Functions
H5PL_type_t H5PLget_plugin_type (void)
const void * H5PLget_plugin_info (void)
hid_t type_convert (xtc_data_type xtc_type)
unsigned long new_xtc_h5token (H5O_token_t *token)
int xtc_h5token_cmp (H5O_token_t *t1, H5O_token_t *t2)
char * xtc_h5token_to_str (const H5O_token_t *t)
int token_copy (H5O_token_t **dst_in_out, H5O_token_t *src_in)
H5VL_xtc_t * _internal_obj_lookup_by_name (H5VL_xtc_t *base_obj, const char *path)
H5VL_xtc_t * _object_lookup (H5VL_xtc_t *base_obj, const H5VL_loc_params_t *loc_params)
hid_t H5VL_xtc_register (void)
int loop_children (bool recursive, xtc_object *xtc_obj, H5L_iterate2_t *op, void *op_data)
int _xtc_object_get_info (H5VL_xtc_t *xtc_obj, H5O_info2_t *oinfo_out, unsigned fields)
Variables
const H5VL_class_t H5VL_xtc_g
Detailed Description
The actual XTC_VOL connector implementation.
Definition in file xtc_vol.c.
Macro Definition Documentation
DEBUG_PRINT
#define DEBUG_PRINT
Definition at line 33 of file xtc_vol.c.
Typedef Documentation
H5VL_xtc_t
typedef struct H5VL_xtc_t H5VL_xtc_t
H5VL_xtc_wrap_ctx_t
typedef struct H5VL_xtc_wrap_ctx_t H5VL_xtc_wrap_ctx_t
Function Documentation
_internal_obj_lookup_by_name()
H5VL_xtc_t* _internal_obj_lookup_by_name (H5VL_xtc_t * base_obj, const char * path)
Definition at line 346 of file xtc_vol.c.
{
     H5VL_xtc_t* ret_obj = NULL;
     assert(base_obj && path && strlen(path) > 0);
     if(strlen(path) == 1){// . or /
         //case '.' for relative path points to self.
         if(path[0] == '.'){
             assert(base_obj->xtc_obj && base_obj->xtc_obj->obj_path_abs);
             ret_obj = base_obj;
         } else if(path[0] == '/') {
             assert(strcmp(base_obj->xtc_obj->obj_path_abs, "/") == 0);
             ret_obj = base_obj;
         } else {
             assert(0 && "_internal_obj_lookup_by_name(): Not implemented.");
         }
         return ret_obj;
     }
     //assert(base_obj->xtc_obj_type = XTC_GROUP);
     char* abs_path = NULL;
     if(path[0] == '.' && path[1] == '/'){//relative path.
         int size = strlen(base_obj->xtc_obj->obj_path_abs) + strlen(path) + 3;
         abs_path = (char*)calloc(1, size*sizeof(char));
         sprintf(abs_path, "%s/%s", base_obj->obj_path, path);
     }
     if(path[0] == '/'){//absolute path.
         abs_path = (char*)path;
     }
     //printf("%s:  absolute path = %s\n", __func__, abs_path);
     DEBUG_PRINT
     xtc_object* obj = xtc_obj_find(base_obj->xtc_obj, abs_path);
     ret_obj = H5VL_xtc_new_obj(obj);
     return ret_obj;
 }
References DEBUG_PRINT, H5VL_xtc_t::obj_path, XTC_C_API_HELPER::obj_path_abs, H5VL_xtc_t::xtc_obj, and xtc_obj_find().
Referenced by _object_lookup().
_object_lookup()
H5VL_xtc_t* _object_lookup (H5VL_xtc_t * base_obj, const H5VL_loc_params_t * loc_params)
Definition at line 381 of file xtc_vol.c.
{
     H5VL_xtc_t* target = NULL;
     switch(loc_params->type){
         case H5VL_OBJECT_BY_SELF:
             //printf("%s:%d: loc_type = H5VL_OBJECT_BY_SELF\n", __func__, __LINE__);// "/"
             target = base_obj;
             break;
         case H5VL_OBJECT_BY_NAME:
 //            printf("%s:%d: loc_type = H5VL_OBJECT_BY_NAME, name = %s, loc_obj_type = %d, base_obj_type = %d\n",
 //                    __func__, __LINE__, loc_params->loc_data.loc_by_name.name, loc_params->obj_type, base_obj->xtc_obj->obj_type);
             //need to handle relative/absolute and find the correct obj
             //base_obj is the obj that's used to start on, search key is in loc_params.
             target = _internal_obj_lookup_by_name(base_obj, loc_params->loc_data.loc_by_name.name);
             break;
         case H5VL_OBJECT_BY_IDX:
             printf("%s:%d: loc_type = H5VL_OBJECT_BY_IDX\n", __func__, __LINE__);
             assert(0 && "Not implemented");
             break;
         case H5VL_OBJECT_BY_TOKEN:
             printf("%s:%d: loc_type = H5VL_OBJECT_BY_TOKEN\n", __func__, __LINE__);
             assert(0 && "Not implemented");
             break;
         default:
             printf("%s:%d: type = Unknown loc_type: %d \n", __func__, loc_params->type, __LINE__);
             break;
     }
     return target;
 }
References _internal_obj_lookup_by_name().
_xtc_object_get_info()
int _xtc_object_get_info (H5VL_xtc_t * xtc_obj, H5O_info2_t * oinfo_out, unsigned fields)
Definition at line 2640 of file xtc_vol.c.
{
     DEBUG_PRINT
     assert(xtc_obj && oinfo_out);
     if(fields & H5O_INFO_BASIC){//meaning fields is H5O_INFO_BASIC
         switch(xtc_obj->xtc_obj_type){
             case XTC_FILE:
                 oinfo_out->type = H5O_TYPE_GROUP;
                 break;
             case XTC_HEAD:
             case XTC_GROUP:
                 oinfo_out->type = H5O_TYPE_GROUP;
                 break;
             case XTC_TIME_DS:
             case XTC_DS:
                 oinfo_out->type = H5O_TYPE_DATASET;
                 break;
             default:
                 printf("Unknown xtc_obj type: %d\n", xtc_obj->xtc_obj_type);
                 assert(0);
                 break;
         }
         oinfo_out->fileno = xtc_obj->xtc_obj->fd;//fd
         oinfo_out->rc = 1;//keep it to 1.
         assert(xtc_obj->xtc_obj->obj_token);
         oinfo_out->token = *(H5O_token_t*)(xtc_obj->xtc_obj->obj_token);// Unique ID for xtc object in current runtime scope.
     }
     if(fields & H5O_INFO_TIME){
         oinfo_out->atime = 0;
         oinfo_out->btime = 0;
         oinfo_out->ctime = 0;
         oinfo_out->mtime = 0;
     }
     if(fields & H5O_INFO_NUM_ATTRS){
         oinfo_out->num_attrs = 0;
     }
     return 0;
 }
References DEBUG_PRINT, XTC_C_API_HELPER::fd, XTC_C_API_HELPER::obj_token, XTC_DS, XTC_FILE, XTC_GROUP, XTC_HEAD, H5VL_xtc_t::xtc_obj, H5VL_xtc_t::xtc_obj_type, and XTC_TIME_DS.
H5PLget_plugin_info()
const void* H5PLget_plugin_info (void)
Definition at line 312 of file xtc_vol.c.
 {return &H5VL_xtc_g;}
References H5VL_xtc_g.
H5PLget_plugin_type()
H5PL_type_t H5PLget_plugin_type (void)
Definition at line 311 of file xtc_vol.c.
 {return H5PL_TYPE_VOL;}
H5VL_xtc_register()
hid_t H5VL_xtc_register (void)
Definition at line 509 of file xtc_vol.c.
 {
     DEBUG_PRINT
     assert(0 && "breakpoint");
     /* Singleton register the xtc VOL connector ID */
     if(H5VL_XTC_g < 0)
         H5VL_XTC_g = H5VLregister_connector(&H5VL_xtc_g, H5P_DEFAULT);
     return H5VL_XTC_g;
 } /* end H5VL_xtc_register() */
References DEBUG_PRINT.
loop_children()
int loop_children (bool recursive, xtc_object * xtc_obj, H5L_iterate2_t * op, void * op_data)
Definition at line 2426 of file xtc_vol.c.
{
     if(!xtc_obj){
         printf("%s: null xtc_obj. return.\n", __func__);
         return 0;
     }
     int n_children = 0;
     xtc_object** children = xtc_get_children_list(xtc_obj, &n_children);
     hid_t gid = H5VLwrap_register(xtc_obj, H5I_GROUP);//obj
     if(n_children == 0 || !children){
         H5Idec_ref(gid);
         return H5_ITER_CONT;
     }
     assert(children && *children);
     for(int i = 0; i < n_children; i++){// iterate xtc_obj group
         char* link_name = children[i]->obj_path_abs;
         H5L_info2_t linfo;
         linfo.type = H5L_TYPE_HARD;
         linfo.corder_valid = false;
         linfo.corder = 0;
         linfo.cset = 0; //US ASCII
         linfo.u.token = *(H5O_token_t*)(children[i]->obj_token);
         int op_ret =  (*op)(gid, link_name, &linfo, op_data);//list metadata of children[i]
         if(op_ret != H5_ITER_CONT){
             H5Idec_ref(gid);
             return op_ret;
         }
         if(recursive && children[i]->obj_type == XTC_GROUP){
             op_ret = loop_children(recursive, children[i], op, op_data);
             if(op_ret != H5_ITER_CONT){
                 H5Idec_ref(gid);
                 return op_ret;
             }
         }
     }//end for(children)
     H5Idec_ref(gid);
     return H5_ITER_CONT;
 }
References XTC_C_API_HELPER::obj_path_abs, xtc_get_children_list(), and XTC_GROUP.
new_xtc_h5token()
unsigned long new_xtc_h5token (H5O_token_t * token)
Definition at line 316 of file xtc_vol.c.
{
     assert(token);
     return xtc_h5token_new((xtc_token_t**)(&token), H5O_MAX_TOKEN_SIZE);
 }
References xtc_h5token_new().
token_copy()
int token_copy (H5O_token_t ** dst_in_out, H5O_token_t * src_in)
Definition at line 339 of file xtc_vol.c.
{
     assert(*dst_in_out && src_in);
     for(int i = 0; i < H5O_MAX_TOKEN_SIZE; i++)
         (*dst_in_out)->__data[i] = src_in->__data[i];
     return 0;
 }
type_convert()
hid_t type_convert (xtc_data_type xtc_type)
xtc2 to HDF5 native data type conversion
Definition at line 1400 of file xtc_vol.c.
{
     char* xtc_type_name = "";
     char* h5_type_name = "";
     hid_t ret;
     switch(xtc_type){
         case UINT8:
             xtc_type_name = "UINT8";
             ret =  H5T_NATIVE_UINT8;
             h5_type_name = "H5T_NATIVE_UINT8";
             break;
         case UINT16:
             xtc_type_name = "UINT16";
             ret = H5T_NATIVE_UINT16;
             h5_type_name = "H5T_NATIVE_UINT16";
             break;
         case UINT32:
             xtc_type_name = "UINT32";
             ret = H5T_NATIVE_UINT32;
             h5_type_name = "H5T_NATIVE_UINT32";
             break;
         case UINT64:
             xtc_type_name = "UINT64";
             ret = H5T_NATIVE_UINT64;
             h5_type_name = "H5T_NATIVE_UINT64";
             break;
         case INT8:
             xtc_type_name = "INT8";
             ret = H5T_NATIVE_INT8;
             h5_type_name = "H5T_NATIVE_INT8";
             break;
         case INT16:
             xtc_type_name = "INT16";
             ret = H5T_NATIVE_INT16;
             h5_type_name = "H5T_NATIVE_INT16";
             break;
         case INT32:
             xtc_type_name = "INT32";
             ret = H5T_NATIVE_INT32;
             h5_type_name = "H5T_NATIVE_INT32";
             break;
         case INT64:
             xtc_type_name = "INT64";
             ret = H5T_NATIVE_INT64;
             h5_type_name = "H5T_NATIVE_INT64";
             break;
         case FLOAT:
             xtc_type_name = "FLOAT";
             ret = H5T_NATIVE_FLOAT;
             h5_type_name = "H5T_NATIVE_FLOAT";
             break;
         case DOUBLE:
             xtc_type_name = "DOUBLE";
             ret = H5T_NATIVE_DOUBLE;
             h5_type_name = "H5T_NATIVE_DOUBLE";
             break;
         case CHARSTR:
             xtc_type_name = "CHARSTR";
             //ret = H5T_C_S1; //C-specific string datatype
             h5_type_name = "H5T_C_S1";
             ret = H5Tcopy(H5T_C_S1);
             H5Tset_size(ret, H5T_VARIABLE);
             break;
         case ENUMVAL:
             xtc_type_name = "ENUMVAL";
             ret = H5T_NATIVE_INT32;
             h5_type_name = "H5T_NATIVE_INT32";
             break;
         case ENUMDICT:
             xtc_type_name = "ENUMDICT";
             ret = H5T_NATIVE_INT32;
             h5_type_name = "H5T_NATIVE_INT32";
             break;
          default:
              printf("Unsupported type: %d\n", xtc_type);
              ret = -1;
             assert(0 && "Unknown type.");
             break;
     }
     //printf("xtc_type = %s, return type: %s\n", xtc_type_name, h5_type_name);
     return ret;
 }
References CHARSTR, DOUBLE, ENUMDICT, ENUMVAL, FLOAT, INT16, INT32, INT64, INT8, UINT16, UINT32, UINT64, and UINT8.
xtc_h5token_cmp()
int xtc_h5token_cmp (H5O_token_t * t1, H5O_token_t * t2)
Definition at line 321 of file xtc_vol.c.
{
     assert(t1&&t2);
     for(int i = 0; i < H5O_MAX_TOKEN_SIZE; i++){
         if(t1->__data[i] != t2->__data[i])
             return -1;
     }
     return 0;
 }
xtc_h5token_to_str()
char* xtc_h5token_to_str (const H5O_token_t * t)
Definition at line 330 of file xtc_vol.c.
{
     assert(t);
     // token sample: 123-46-789-1
     char* str = (char*)calloc(1, 18 * sizeof(char));
     sprintf(str, "%d-%d-%d-%d", t->__data[0], t->__data[1], t->__data[2], t->__data[3]);
     //printf("test token_to_str: %s\n", str);
     return str;
 }
Variable Documentation
H5VL_xtc_g
const H5VL_class_t H5VL_xtc_g
Definition at line 200 of file xtc_vol.c.
Referenced by H5PLget_plugin_info().