#!/usr/bin/bash

# condaProcServ
#
# arguments:
#   1:   rcFile
#   2:   condaEnv
#   3:   name
#   4:   waitFlag
#   5:   logFile
#   6:   coreSize
#   7:   ctrlPort
#   8:   pythonVer
#   9+:  [rtprio] [env] cmd [args]
#
# return values:
#   0: success
#   5: invalid arguments
#   6: conda activate failed
#   7: command not found on PATH
#   8: conda.sh not found
#   9: procServ not found
#   10: rcfile not found
#   11: CONDABASE not defined in rcfile
#   12: PROCSERVBIN not defined in rcfile
#   13: CONDA_PREFIX not defined in environment
#   other: procServ error

if (( "$#" < 9 )); then
    echo "usage: ${0} <rcFile> <condaEnv> <name> <waitFlag> <logFile> <coreSize> <ctrlPort> <pythonVer> [<arg1> ...]"
    exit 5
fi

# start with minimal PATH
export PATH="/usr/sbin:/usr/bin:/sbin:/bin"

rcFile="${1}"
condaEnv="${2}"
name="${3}"
waitFlag="${4}"
logFile="${5}"
coreSize="${6}"
ctrlPort="${7}"
# remove .* suffix from ${8}, shortening xx.yy.zz to xx.yy
pythonVer="${8%.*}"
args=""

#for arg in "$@"; do
#    echo "*** " "${arg}" > /tmp/junk_${ctrlPort}.log #${logFile}_2
#done

if (( "$#" > 8 )); then
    shift 8
    args=("$@")
fi

echo "rcFile: '$rcFile'"        # >> /tmp/junk_${ctrlPort}.log #${logFile}_2
echo "condaEnv: '$condaEnv'"    # >> /tmp/junk_${ctrlPort}.log #${logFile}_2
echo "name: '$name'"            # >> /tmp/junk_${ctrlPort}.log #${logFile}_2
echo "waitFlag: '$waitFlag'"    # >> /tmp/junk_${ctrlPort}.log #${logFile}_2
echo "logFile: '$logFile'"      # >> /tmp/junk_${ctrlPort}.log #${logFile}_2
echo "coreSize: '$coreSize'"    # >> /tmp/junk_${ctrlPort}.log #${logFile}_2
echo "ctrlPort: '$ctrlPort'"    # >> /tmp/junk_${ctrlPort}.log #${logFile}_2
echo "pythonVer: '$pythonVer'"  # >> /tmp/junk_${ctrlPort}.log #${logFile}_2
echo "args: '${args[@]}'"       # >> /tmp/junk_${ctrlPort}.log #${logFile}_2

if [[ -z $rcFile ]]; then
    echo "error: no rcfile specified"
    exit 5
fi

# read rcfile
if [[ ! -f $rcFile ]]; then
    echo "error: $rcFile not found"
    exit 10
else
    . $rcFile
fi

if [[ -z $PROCSERVBIN ]]; then
    echo "error: PROCSERVBIN not defined in $rcFile"
    exit 12
fi

if [[ ! -z $condaEnv ]]; then
    if [[ -z $CONDABASE ]]; then
        echo "error: CONDABASE not defined in $rcFile"
        exit 11
    fi
    if [ -f $CONDABASE/etc/profile.d/conda.sh ]; then
        source $CONDABASE/etc/profile.d/conda.sh
    else
        echo "error: conda.sh not found"
        exit 8
    fi
#   if ! conda activate "$condaEnv"; then
#       echo "error: conda activate $condaEnv"
#       exit 6
#   fi
fi

if ! [[ -v CONDA_PREFIX ]]; then
    echo "error: CONDA_PREFIX not defined in environment"
    exit 13
fi

# update paths
if [[ -v TESTRELDIR ]]; then
    echo "TESTRELDIR=${TESTRELDIR}"
    echo "CONDA_PREFIX=${CONDA_PREFIX}"
    # TESTRELDIR before condaEnv in PATH
    export PATH="${TESTRELDIR}/bin:${CONDA_PREFIX}/bin:$CONDA_PREFIX/epics/bin/linux-x86_64:${PATH}"
    # SET LD_LIBRARY_PATH
    export LD_LIBRARY_PATH="${TESTRELDIR}/lib"
    if [ ! -z $pythonVer ]; then
        # SET PYTHONPATH
        export PYTHONPATH="${TESTRELDIR}/lib/python${pythonVer}/site-packages"
    fi
else
    echo "CONDA_PREFIX=${CONDA_PREFIX}"
    export PATH="${CONDA_PREFIX}/bin:$CONDA_PREFIX/epics/bin/linux-x86_64:${PATH}"
fi

if [[ -z $logFile ]]; then
    logFlag=""
else
    logFlag="-L $logFile"
fi

if [[ -z $waitFlag ]]; then
    waitFlag=""
fi

# workaround bug in procServ where --coresize option was
# stored in a 32-bit int, which limits core sizes to 2GB.
ulimit -c $coreSize

if [[ -f $PROCSERVBIN ]]; then
    #echo "***" $PROCSERVBIN \
    #    --noautorestart --name $name --pidfile /dev/null $waitFlag $logFlag --allow \
    #    $ctrlPort "${args[@]}"  >> /tmp/junk_${ctrlPort}.log # ${logFile}_2
    $PROCSERVBIN \
        --noautorestart --name $name --pidfile /dev/null $waitFlag $logFlag --allow \
        $ctrlPort "${args[@]}" # &>> /tmp/junk2_${ctrlPort}.log
    #$PROCSERVBIN \
    #    --noautorestart --name $name --pidfile /dev/null $waitFlag $logFlag --allow \
    #    $ctrlPort "/bin/env" "EPICS_PVA_ADDR_LIST=172.21.152.78 172.27.131.255"     \
    #    "LD_LIBRARY_PATH=/cds/sw/ds/ana/conda2/inst/envs/ps-4.6.1/epics/lib/linux-x86_64:/cds/sw/ds/ana/conda2/inst/envs/ps-4.6.1/pcas/lib/linux-x86_64" \
    #    $cmd "${args[@]}"
else
    echo "error: procServ not found"
    exit 9
fi

rv=$?

if [[ "$rv" -ne 0 ]]; then
    echo "error: procServ returned $rv"
fi

exit $rv
