# Package level makefile
# ----------------------

# Checks
# ------
# Check release location variables

include ../setup.mk

ifndef PREMAKE_DONE
include ../premake.mk
else
include constituents.mk
include ../package.mk
endif

Makefile:;
constituents.mk:;