#!/bin/bash -f
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
ARG=$1
shift 1
pushd ../../..
source setup_env.sh
conda activate ps-1.0.4
popd
rm -rf temp.db
mkdir temp.db
exec mongod --bind_ip_all --dbpath temp.db --port $ARG --logpath /dev/null --replSet test
