#!/bin/bash
source /reg/g/psdm/sw/conda2/manage/bin/psconda.sh ""
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export PATH=$SCRIPTDIR/../../../install/bin:${PATH}
export EPICS_CA_SERVER_PORT=5066
export EPICS_CA_REPEATER_PORT=5067
python "$@"
