#!/bin/bash
# psconda.sh takes arguments to optionally select a py2 environment
# we want py3 here, so we pass ""
source /reg/g/psdm/sw/conda2/manage/bin/psconda.sh ""
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export PATH=$SCRIPTDIR/../../../install/bin:${PATH}
export EPICS_CA_SERVER_PORT=5066
export EPICS_CA_REPEATER_PORT=5067
export EPICS_CA_ADDR_LIST=10.0.3.255
export EPICS_CA_AUTO_ADDR_LIST=NO
python "$@"
