cp /cds/group/pcds/dist/pds/tmo/scripts/tmo.cnf .
cp /cds/group/pcds/dist/pds/rix/scripts/rix.cnf .
cp /cds/group/pcds/dist/pds/ued/scripts/ued.cnf .
cp /cds/group/pcds/dist/pds/tmo/scripts/hsd.cnf .
cp /cds/group/pcds/dist/pds/tmo/scripts/neh-base.cnf .
cp /cds/group/pcds/dist/pds/rix/scripts/rix-hsd.cnf .
cp /cds/group/pcds/dist/pds/tmo/scripts/setup_env.sh setup_env_tmo.sh
cp /cds/group/pcds/dist/pds/rix/scripts/setup_env.sh setup_env_rix.sh
cp /cds/group/pcds/dist/pds/ued/scripts/setup_env.sh setup_env_ued.sh
