#--------------------------------------------------------------------------
# File and Version Information:
#  $Id$
#
# Description:
#  README file for package psalgos
#------------------------------------------------------------------------

Package author: Mikhail S. Dubrovin

Brief description:
==================

Add here a brief description of the package main purpose, one or two
sentences is probably enough.

Detailed description:
=====================

More detailed info goes here. Describe main classes/applications built in
this package. Give few examples of their use.
